FishAndPlaces\Domain\Fish\Model\FishImage:
    repositoryClass: FishAndPlaces\Infrastructure\Fish\Repository\Doctrine\ORM\DoctrineFishImageRepository
    type: entity
    table: fish_image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        createdAt:
            type: datetime
        updateAt:
            type: datetime
            nullable: true
        imageSrc:
            type: string

    ManyToOne:
        image:
            targetEntity: Fish
            inversedBy: fishImages
            joinColumn:
                name: fish_id
                referencedColumnName: id
